import type { AppSnapshot } from "../types";

export const mockSnapshot: AppSnapshot = {
  accounts: [
    {
      id: "acc_primary",
      email: "smonchamps@gmail.com",
      displayName: "Sebastien Monchamps",
      color: "#3B82F6",
      status: "connected",
      unreadCount: 3,
    },
    {
      id: "acc_work",
      email: "sebastien@discovery.mail",
      displayName: "Discovery Work",
      color: "#EF4444",
      status: "syncing",
      unreadCount: 5,
    },
  ],
  mailboxes: [
    { id: "mail_unified", kind: "unified_inbox", label: "Unified Inbox", unreadCount: 8 },
    { id: "mail_inbox_primary", accountId: "acc_primary", kind: "inbox", label: "Inbox", unreadCount: 3 },
    { id: "mail_drafts_primary", accountId: "acc_primary", kind: "drafts", label: "Drafts", unreadCount: 1 },
    { id: "mail_sent_primary", accountId: "acc_primary", kind: "sent", label: "Sent", unreadCount: 0 },
    { id: "mail_archive_primary", accountId: "acc_primary", kind: "archive", label: "Archive", unreadCount: 0 },
    { id: "mail_spam_primary", accountId: "acc_primary", kind: "spam", label: "Spam", unreadCount: 0 },
    { id: "mail_inbox_work", accountId: "acc_work", kind: "inbox", label: "Inbox", unreadCount: 5 },
    { id: "mail_drafts_work", accountId: "acc_work", kind: "drafts", label: "Drafts", unreadCount: 0 },
    { id: "mail_sent_work", accountId: "acc_work", kind: "sent", label: "Sent", unreadCount: 0 },
    { id: "mail_archive_work", accountId: "acc_work", kind: "archive", label: "Archive", unreadCount: 0 },
    { id: "mail_spam_work", accountId: "acc_work", kind: "spam", label: "Spam", unreadCount: 0 },
  ],
  selectedMailboxId: "mail_unified",
  syncStatus: {
    acc_primary: {
      state: "idle",
      lastSuccessfulSyncAt: "2026-04-05T10:42:00Z",
      detail: "Mailbox is up to date.",
    },
    acc_work: {
      state: "syncing",
      lastSuccessfulSyncAt: "2026-04-05T10:37:00Z",
      detail: "Syncing the latest inbox changes.",
    },
  },
  threads: [
    {
      id: "thread_masterclass",
      accountId: "acc_primary",
      mailboxId: "mail_inbox_primary",
      subject: "Why you get overlooked at work (and how to fix it)",
      snippet: "Build the influence, voice, and mindset that get you noticed.",
      from: { name: "MasterClass", email: "news@masterclass.com" },
      receivedAt: "2026-04-05T10:43:00Z",
      isUnread: true,
      hasAttachments: false,
      badge: "M",
    },
    {
      id: "thread_stock",
      accountId: "acc_work",
      mailboxId: "mail_inbox_work",
      subject: "La Vente de Stock du mois vient d’ouvrir",
      snippet: "On vous livre en quelques jours seulement.",
      from: { name: "ASPHALTE Homme", email: "news@asphalte.com" },
      receivedAt: "2026-04-05T10:02:00Z",
      isUnread: true,
      hasAttachments: false,
      badge: "AH",
    },
    {
      id: "thread_apec",
      accountId: "acc_work",
      mailboxId: "mail_inbox_work",
      subject: "3 minutes pour évaluer l’APEC",
      snippet: "Si vous avez des difficultés pour visualiser ce message, cliquez ici.",
      from: { name: "APEC", email: "info@apec.fr" },
      receivedAt: "2026-04-05T06:08:00Z",
      isUnread: true,
      hasAttachments: false,
      badge: "A",
    },
    {
      id: "thread_spark",
      accountId: "acc_primary",
      mailboxId: "mail_inbox_primary",
      subject: "Utilisez Spark pour acquérir de meilleures habitudes",
      snippet: "Centre de contrôle. Créez de meilleures habitudes email.",
      from: { name: "Team Spark", email: "spark@readdle.com" },
      receivedAt: "2026-04-05T02:20:00Z",
      isUnread: false,
      hasAttachments: false,
      badge: "S",
    },
  ],
  allThreads: [
    {
      id: "thread_masterclass",
      accountId: "acc_primary",
      mailboxId: "mail_inbox_primary",
      subject: "Why you get overlooked at work (and how to fix it)",
      snippet: "Build the influence, voice, and mindset that get you noticed.",
      from: { name: "MasterClass", email: "news@masterclass.com" },
      receivedAt: "2026-04-05T10:43:00Z",
      isUnread: true,
      hasAttachments: false,
      badge: "M",
    },
    {
      id: "thread_stock",
      accountId: "acc_work",
      mailboxId: "mail_inbox_work",
      subject: "La Vente de Stock du mois vient d’ouvrir",
      snippet: "On vous livre en quelques jours seulement.",
      from: { name: "ASPHALTE Homme", email: "news@asphalte.com" },
      receivedAt: "2026-04-05T10:02:00Z",
      isUnread: true,
      hasAttachments: false,
      badge: "AH",
    },
    {
      id: "thread_apec",
      accountId: "acc_work",
      mailboxId: "mail_inbox_work",
      subject: "3 minutes pour évaluer l’APEC",
      snippet: "Si vous avez des difficultés pour visualiser ce message, cliquez ici.",
      from: { name: "APEC", email: "info@apec.fr" },
      receivedAt: "2026-04-05T06:08:00Z",
      isUnread: true,
      hasAttachments: false,
      badge: "A",
    },
    {
      id: "thread_spark",
      accountId: "acc_primary",
      mailboxId: "mail_inbox_primary",
      subject: "Utilisez Spark pour acquérir de meilleures habitudes",
      snippet: "Centre de contrôle. Créez de meilleures habitudes email.",
      from: { name: "Team Spark", email: "spark@readdle.com" },
      receivedAt: "2026-04-05T02:20:00Z",
      isUnread: false,
      hasAttachments: false,
      badge: "S",
    },
  ],
  selectedThreadId: "thread_masterclass",
  threadDetail: {
    id: "thread_masterclass",
    accountId: "acc_primary",
    mailboxId: "mail_inbox_primary",
    subject: "Why you get overlooked at work (and how to fix it)",
    participants: [
      { name: "MasterClass", email: "news@masterclass.com" },
      { name: "Sebastien Monchamps", email: "smonchamps@gmail.com" },
    ],
    receivedAt: "2026-04-05T10:43:00Z",
    badge: "M",
    messages: [
      {
        id: "msg_masterclass",
        from: { name: "MasterClass", email: "news@masterclass.com" },
        to: [{ name: "Sebastien Monchamps", email: "smonchamps@gmail.com" }],
        sentAt: "2026-04-05T10:43:00Z",
        htmlBody:
          "<div style='max-width:540px;margin:0 auto;background:#050505;color:#f5f5f5;font-family:Arial,sans-serif;border-radius:18px;overflow:hidden'><div style='padding:32px 32px 16px;text-align:center;background:#0b0b0c'><div style='font-size:28px;font-weight:700;letter-spacing:.06em;color:#ff3b6b'>MasterClass</div></div><div style='padding:32px'><h1 style='font-size:46px;line-height:1.02;margin:0 0 18px;font-weight:800;text-transform:uppercase'>How to turn your hard work into real recognition</h1><p style='font-size:18px;line-height:1.6;color:#dddddd;margin:0 0 24px'>You do the work. You have the ideas. With the right tools, your ambition becomes impossible to ignore.</p><a style='display:inline-block;padding:16px 24px;background:#ff3b6b;border-radius:14px;color:white;text-decoration:none;font-weight:700' href='https://www.masterclass.com'>Get MasterClass</a></div></div>",
        textBody:
          "How to turn your hard work into real recognition. You do the work. You have the ideas. With the right tools, your ambition becomes impossible to ignore.",
        attachments: [],
      },
    ],
  },
  drafts: [
    {
      id: "draft_1",
      accountId: "acc_primary",
      mailboxId: "mail_drafts_primary",
      to: ["hello@example.com"],
      cc: [],
      bcc: [],
      subject: "Discovery alpha notes",
      updatedAt: "2026-04-05T09:40:00Z",
    },
  ],
  activeDraft: {
    envelope: {
      id: "draft_1",
      accountId: "acc_primary",
      mailboxId: "mail_drafts_primary",
      to: ["hello@example.com"],
      cc: [],
      bcc: [],
      subject: "Discovery alpha notes",
      updatedAt: "2026-04-05T09:40:00Z",
    },
    content: {
      htmlBody: "<p>Here is the latest Discovery alpha progress.</p>",
      textBody: "Here is the latest Discovery alpha progress.",
      attachments: [],
    },
  },
};
